POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test Blog 3",
  "author": "Test Author",
  "url": "http://test.com",
  "likes": 3
}

###

GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "testpassword"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ab",
  "name": "Invalid Username",
  "password": "Invalid Username"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Invalid Password",
  "name": "Invalid Password",
  "password": "ab"
}

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}